"use node";

import { openai } from "@ai-sdk/openai";
import { stepCountIs, ToolLoopAgent } from "ai";
import { v } from "convex/values";
import {
	buildWorkspaceToolSet,
	type WorkspaceToolConnection,
} from "../packages/ai/src/workspace-tool-registry.mjs";
import { getChatModelProviderOptions } from "../packages/ai/src/models.mjs";
import { finalizeOpenAIToolSet } from "../packages/ai/src/openai-tool-search.mjs";
import { BASE_CHAT_SYSTEM_PROMPT } from "../packages/ai/src/prompts.mjs";
import { internal } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { internalAction, type ActionCtx } from "./_generated/server";
import { listYandexUpcomingEvents } from "./yandexCalendar";

const MAX_AUTOMATION_HISTORY_MESSAGES = 40;

const automationRunReasonValidator = v.union(
	v.literal("scheduled"),
	v.literal("manual"),
);

const createMessageId = () =>
	`msg-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

const createTextMessage = ({
	id,
	role,
	text,
	metadata,
}: {
	id: string;
	role: "user" | "assistant";
	text: string;
	metadata: Record<string, unknown>;
}) => ({
	id,
	role,
	partsJson: JSON.stringify([{ type: "text", text }]),
	metadataJson: JSON.stringify(metadata),
	text,
	createdAt: Date.now(),
});

const buildAutomationYandexCalendarAdapter = () => (connection: {
	displayName: string;
	email: string;
	password: string;
	serverAddress: string;
	calendarHomePath: string;
}) => ({
	listUpcomingEvents: async ({ lookaheadMs }: { lookaheadMs: number }) => {
		const now = Date.now();
		const result = await listYandexUpcomingEvents({
			connection,
			now,
			timeMin: now,
			timeMax: now + lookaheadMs,
		});

		return {
			connection: connection.displayName,
			events: result.events,
		};
	},
});

const getAutomationAppTools = async (
	ctx: ActionCtx,
	run: {
		appsEnabled: boolean;
		appSources: Array<{ id: string }>;
		ownerTokenIdentifier: string;
		workspaceId: Id<"workspaces">;
	},
) => {
	if (!run.appsEnabled) {
		return {};
	}

	const sourceIds = run.appSources
		.map((source) => source.id)
		.filter((sourceId) => sourceId.startsWith("app:"));

	if (sourceIds.length === 0) {
		return {};
	}

	const connections = await ctx.runAction(
		internal.appConnectionActions.getSelectedForChatInternalWithFreshTokens,
		{
			ownerTokenIdentifier: run.ownerTokenIdentifier,
			workspaceId: run.workspaceId,
			sourceIds,
		},
	);

	return await buildWorkspaceToolSet(connections as WorkspaceToolConnection[], {
		yandexCalendar: buildAutomationYandexCalendarAdapter(),
	});
};

const buildAutomationSystemPrompt = ({
	targetLabel,
	webSearchEnabled,
	appSources,
	notes,
}: {
	targetLabel: string;
	webSearchEnabled: boolean;
	appSources: Array<{ label: string }>;
	notes: Array<{ title: string; text: string; updatedAt: number }>;
}) => {
	const noteContext = notes
		.map((note) =>
			[
				`Title: ${note.title}`,
				`Updated: ${new Date(note.updatedAt).toISOString()}`,
				note.text,
			].join("\n"),
		)
		.join("\n\n---\n\n");

	return [
		BASE_CHAT_SYSTEM_PROMPT,
		"This response is being generated by a scheduled automation.",
		`Automation target: ${targetLabel}.`,
		webSearchEnabled
			? "Web search is enabled. Use web search when current or external information is needed."
			: "",
		appSources.length > 0
			? `Selected sources: ${appSources.map((source) => source.label).join(", ")}.`
			: "",
		"Use the automation prompt as the task. If project notes are provided, use them as context and do not invent missing facts.",
		noteContext ? `Recent project notes:\n\n${noteContext}` : "",
	]
		.filter(Boolean)
		.join("\n\n");
};

export const runAutomation = internalAction({
	args: {
		automationId: v.id("automations"),
		scheduledFor: v.number(),
		reason: automationRunReasonValidator,
	},
	returns: v.null(),
	handler: async (ctx, args) => {
		if (!process.env.OPENAI_API_KEY) {
			throw new Error("OPENAI_API_KEY is not configured in Convex.");
		}

		const run = await ctx.runMutation(internal.automations.beginRun, args);
		if (run.status === "skipped") {
			return null;
		}

		const userMessageId = createMessageId();
		const assistantMessageId = createMessageId();
		const metadata = {
			source: "automation",
			automationId: String(run.automationId),
			automationRunId: String(run.runId),
			scheduledFor: run.scheduledFor,
			reason: run.reason,
		};

		try {
			await ctx.runMutation(internal.chats.saveMessageForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				authorName: run.authorName,
				chatId: run.chatId,
				title: run.title,
				preview: run.prompt,
				model: run.model,
				reasoningEffort: run.reasoningEffort,
				forceTitle: true,
				message: createTextMessage({
					id: userMessageId,
					role: "user",
					text: run.prompt,
					metadata,
				}),
			});

			const history = await ctx.runQuery(internal.chats.getMessagesForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				chatId: run.chatId,
			});
			const messages = history
				.slice(-MAX_AUTOMATION_HISTORY_MESSAGES)
				.filter(
					(message) =>
						(message.role === "user" || message.role === "assistant") &&
						message.text.trim(),
				)
				.map((message) => ({
					role: message.role,
					content: message.text,
				}));
			const appTools = await getAutomationAppTools(ctx, run);
			const finalizedToolSet = finalizeOpenAIToolSet({
				...(run.webSearchEnabled
					? {
							web_search: openai.tools.webSearch({
								searchContextSize: "medium",
								userLocation: {
									type: "approximate" as const,
									country: "US" as const,
								},
							}),
						}
					: {}),
				...appTools,
			});
			const { tools } = finalizedToolSet;
			const automationAgent = new ToolLoopAgent({
				id: "automation-runner",
				model: openai(run.model),
				providerOptions: getChatModelProviderOptions(run.model, {
					reasoningEffort: run.reasoningEffort,
				}),
				instructions: buildAutomationSystemPrompt({
					targetLabel: run.targetLabel,
					webSearchEnabled: run.webSearchEnabled,
					appSources: run.appSources,
					notes: run.notes,
				}),
				tools: finalizedToolSet.hasTools ? tools : undefined,
				stopWhen: finalizedToolSet.hasTools ? stepCountIs(5) : undefined,
			});
			const result = await automationAgent.generate({
				messages,
			});

			await ctx.runMutation(internal.chats.saveMessageForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				authorName: run.authorName,
				chatId: run.chatId,
				title: run.title,
				preview: result.text,
				model: run.model,
				reasoningEffort: run.reasoningEffort,
				forceTitle: true,
				message: createTextMessage({
					id: assistantMessageId,
					role: "assistant",
					text: result.text,
					metadata,
				}),
			});

			await ctx.runMutation(internal.automations.completeRun, {
				automationId: run.automationId,
				runId: run.runId,
				userMessageId,
				assistantMessageId,
			});
		} catch (error) {
			const errorMessage = error instanceof Error ? error.message : String(error);
			try {
				await ctx.runMutation(internal.chats.saveMessageForOwner, {
					ownerTokenIdentifier: run.ownerTokenIdentifier,
					workspaceId: run.workspaceId,
					authorName: run.authorName,
					chatId: run.chatId,
					title: run.title,
					preview: "Automation run failed.",
					model: run.model,
					reasoningEffort: run.reasoningEffort,
					forceTitle: true,
					message: createTextMessage({
						id: assistantMessageId,
						role: "assistant",
						text: [
							"Automation run failed.",
							"",
							"I could not complete this scheduled run. The automation remains scheduled for future runs unless it is paused or deleted.",
						].join("\n"),
						metadata: {
							...metadata,
							event: "failed",
							error: errorMessage,
						},
					}),
				});
			} catch (messageError) {
				console.error(
					"Failed to save automation failure message",
					messageError,
				);
			}
			await ctx.runMutation(internal.automations.failRun, {
				automationId: run.automationId,
				runId: run.runId,
				error: errorMessage,
			});
			throw error;
		}

		return null;
	},
});
